// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'hipster';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String GITHUB = 'assets/github.svg';
  static const String LINKEDIN = 'assets/linkedin.svg';
  static const String LOGO = 'assets/logo.png';
}
